#pragma once

#include <cinttypes>
#include <cstddef>
#include <utility>

#define TAG_BASE 123
#define TAG_VALIDATE TAG_BASE + 1
#define TAG_TIMING TAG_BASE + 2
#define TAG_ALLGATHER_ASYNC TAG_BASE + 3
#define TAG_ALLREDUCE_BUTTERFLY TAG_BASE + 4
#define TAG_ALLREDUCE_BUTTERFLY_REDUCE TAG_BASE + 5
#define TAG_ALLREDUCE_RABENSEIFNER TAG_BASE + 6
#define TAG_RABENSEIFNER_GATHER TAG_BASE + 7
#define TAG_RABENSEIFNER_GATHER_VEC_A TAG_BASE + 8
#define TAG_RABENSEIFNER_GATHER_VEC_B TAG_BASE + 9
#define TAG_RABENSEIFNER_SCATTER TAG_BASE + 10
